# url 里填写自己的订阅,名称不能重复
log-level: info
proxy-providers:
  provider1:
    url: ""
    type: http
    interval: 86400
    proxy: DIRECT
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204", interval: 300}

mixed-port: 31193
ipv6: false
allow-lan: false
unified-delay: true
tcp-concurrent: false
external-controller: 127.0.0.1:41193
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"


find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  device: utun0
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  strict-route: true
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  cache-algorithm: arc
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
    - "rule-set:fake_ip_filter"
    - "rule-set:always_real_ip"
  nameserver: 
    # 运营商DNS
    - 202.96.128.86
    - 211.136.192.6
    - 223.5.5.5

proxy-groups:

  - name: Proxy
    type: select
    proxies: [自动选择,全部节点,香港-Auto,台湾-Auto,日本-Auto,新加坡-Auto,美国-Auto,其它地区]

  - name: 全部节点
    type: select
    include-all: true
    exclude-type: direct
    exclude-filter: "订阅|官网|售后"

  - name: 自动选择
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|🇺🇸|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)(?!.*(?:家宽|专用)).*)"
    exclude-filter: "订阅|官网|售后"
    tolerance: 20
    interval: 300
    lazy: true

  - name: Block
    type: select
    proxies: [REJECT,Proxy,DIRECT]

  - name: Pixiv
    type: select
    proxies: [Pixiv-auto,日本,Proxy,全部节点]
    url: "https://www.pixiv.net"
    interval: 300

  - name: ASMR
    type: select
    proxies: [ASMR-auto,Proxy,全部节点,DIRECT]
    url: "https://asmr.one"
    interval: 300

  - name: Youtube
    type: select
    proxies: [Youtube-auto,Proxy,全部节点]
    url: "https://www.youtube.com"
    interval: 300

  - name: Pixiv-auto
    type: url-test
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore)(?!.*(?:家宽|专用)).*)"
    exclude-filter: "订阅|官网|售后"
    url: "https://www.pixiv.net"
    interval: 300
    tolerance: 30
    hidden: true
    lazy: true

  - name: ASMR-auto
    type: url-test
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore)(?!.*(?:家宽|专用)).*)"
    exclude-filter: "订阅|官网|售后"
    url: "https://asmr.one"
    interval: 300
    tolerance: 30
    hidden: true
    lazy: true

  - name: Youtube-auto
    type: url-test
    url: "https://www.youtube.com"
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|🇺🇸|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates|D1)(?!.*(?:家宽|专用)).*)"
    exclude-filter: "订阅|官网|售后"
    tolerance: 20
    interval: 300
    hidden: true
    lazy: true
    
  - name: AI
    type: select
    proxies:  [美国-Auto]
    include-all: true
    exclude-type: direct
    exclude-filter: "订阅|官网|售后"

  - name: Download
    type: select
    proxies:  [Proxy,DIRECT]
    include-all: true
    exclude-filter: "订阅|官网|售后|家宽|专用"

  - name: Match
    type: select
    proxies:  [DIRECT,Proxy]


  #分隔,下面是地区分组
  - name: 香港-Auto
    type: url-test
    include-all: true
    filter: "(?i)港|hk|hongkong|hong kong"
    exclude-filter: "订阅|官网|售后|家宽|专用"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 台湾-Auto
    type: url-test
    include-all: true
    filter: "(?i)台|tw|taiwan"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 日本-Auto
    type: url-test
    include-all: true
    filter: "(?i)日本|jp|japan"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 美国-Auto
    type: url-test
    include-all: true
    filter: "(?i)美|us|unitedstates|united states"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 新加坡-Auto
    type: url-test
    include-all: true
    filter: "(?i)(新|sg|singapore)"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 日本
    type: select
    proxies: [日本-Auto]
    include-all: true
    filter: "(?i)日本|jp|japan"

  - name: 其它地区
    type: select
    include-all: true
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"
    exclude-filter: "订阅|官网|售后"

rule-providers-anchor: # 锚点 如合并时有重复的项, 则不会去合并; 锚点名不能包含特殊字符
  rule_domain: &rule_domain {type: http, behavior: domain, format: mrs, interval: 43200}
  rule_ipcidr: &rule_ipcidr {type: http, behavior: ipcidr, format: mrs, interval: 43200}
  rule_classical: &rule_classical {type: http, behavior: classical, format: yaml, interval: 43200}

rule-providers:
  pcdn:
    type: http
    url: "https://raw.githubusercontent.com/uselibrary/PCDN/refs/heads/main/pcdn.list"
    format: text
    interval: 43200
    behavior: classical
    proxy: Proxy
    
  always_real_ip:
      type: http
      url: "https://raw.githubusercontent.com/YRSB/MihomoRule/refs/heads/master/always_real_ip.yaml"
      format: yaml
      interval: 43200
      behavior: classical
      proxy: Proxy
      path: ./ruleset/always_real_ip.yaml

  custom_direct:
      type: http
      url: "https://raw.githubusercontent.com/YRSB/MihomoRule/refs/heads/master/custom_direct.yaml"
      format: yaml
      interval: 43200
      behavior: classical
      proxy: Proxy
      path: ./ruleset/custom_direct.yaml
  
  custom_proxy:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/refs/heads/master/custom_proxy.yaml"
    format: yaml
    interval: 43200
    behavior: classical
    proxy: Proxy
    path: ./ruleset/custom_proxy.yaml

  custom_ai:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/refs/heads/master/custom_ai.yaml"
    format: yaml
    interval: 43200
    behavior: domain
    proxy: Proxy
    path: ./ruleset/custom_ai.yaml

  asmr:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/refs/heads/master/asmr.yaml"
    format: yaml
    interval: 43200
    behavior: domain
    proxy: Proxy
    path: ./ruleset/asmr.yaml

  jp:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/refs/heads/master/jp.yaml"
    format: yaml
    interval: 43200
    behavior: classical
    proxy: Proxy
    path: ./ruleset/jp.yaml

  site_googlefcm:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs'
    proxy: Proxy

  site_pixiv:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs'
    proxy: Proxy
  
  site_dmm:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/dmm.mrs'
    proxy: Proxy

  site_dlsite:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/dlsite.mrs'
    proxy: Proxy

  site_youtube:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs'
    proxy: Proxy

  site_geolocation_non_cn:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs'
    proxy: Proxy

  reject_non_ip_no_drop:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt
    path: ./sukkaw_ruleset/reject_non_ip_no_drop.txt
    proxy: Proxy

  reject_non_ip_drop:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt
    path: ./sukkaw_ruleset/reject_non_ip_drop.txt
    proxy: Proxy

  reject_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/reject.txt
    path: ./sukkaw_ruleset/reject_non_ip.txt
    proxy: Proxy

  reject_domainset:
    type: http
    behavior: domain
    format: mrs
    interval: 43200
    url: https://github.com/YRSB/MihomoRule/raw/refs/heads/master/rule/reject_domainset.mrs
    path: ./sukkaw_ruleset/reject_domainset.mrs
    proxy: Proxy

  reject_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/reject.txt
    path: ./sukkaw_ruleset/reject_ip.txt
    proxy: Proxy

  ai_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./sukkaw_ruleset/ai_non_ip.txt
    proxy: Proxy

  telegram_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/telegram.txt
    path: ./sukkaw_ruleset/telegram_ip.txt
    proxy: Proxy

  microsoft_cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
    path: ./sukkaw_ruleset/microsoft_cdn_non_ip.txt
    proxy: Proxy

  microsoft_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
    path: ./sukkaw_ruleset/microsoft_non_ip.txt
    proxy: Proxy

  lan_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./sukkaw_ruleset/lan_non_ip.txt
    proxy: Proxy

  lan_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
    path: ./sukkaw_ruleset/lan_ip.txt
    proxy: Proxy

  domestic_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
    path: ./sukkaw_ruleset/domestic_non_ip.txt
    proxy: Proxy

  direct_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
    path: ./sukkaw_ruleset/direct_non_ip.txt
    proxy: Proxy

  global_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
    path: ./sukkaw_ruleset/global_non_ip.txt
    proxy: Proxy

  domestic_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
    path: ./sukkaw_ruleset/domestic_ip.txt
    proxy: Proxy

  china_ip:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 43200
    url: 'https://github.com/YRSB/MihomoRule/raw/refs/heads/master/rule/china_ip.mrs'
    path: ./sukkaw_ruleset/china_ip.mrs
    proxy: Proxy

  download_domainset:
    type: http
    behavior: domain
    format: mrs
    interval: 43200
    url: 'https://github.com/YRSB/MihomoRule/raw/refs/heads/master/rule/download_domainset.mrs'
    path: ./sukkaw_ruleset/download_domainset.mrs
    proxy: Proxy

  download_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: 'https://ruleset.skk.moe/Clash/non_ip/download.txt'
    path: ./sukkaw_ruleset/download_non_ip.txt
    proxy: Proxy

  cdn_domainset:
    type: http
    behavior: domain
    format: mrs
    interval: 43200
    url: 'https://github.com/YRSB/MihomoRule/raw/refs/heads/master/rule/cdn_domainset.mrs'
    path: ./sukkaw_ruleset/cdn_domainset.mrs
    proxy: Proxy

  cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: 'https://ruleset.skk.moe/Clash/non_ip/cdn.txt'
    path: ./sukkaw_ruleset/cdn_non_ip.txt
    proxy: Proxy

  fake_ip_filter:
    type: http
    behavior: domain
    format: text
    interval: 43200
    url: 'https://ruleset.skk.moe/Clash/domainset/clash_fake_ip_filter.txt'
    path: ./sukkaw_ruleset/clash_fake_ip_filter.txt
    proxy: Proxy
  
  reject_awavenue_ads_rule:
    type: http
    behavior: domain
    format: mrs
    interval: 43200
    url: 'https://github.com/YRSB/MihomoRule/raw/refs/heads/master/rule/awavenue_ads_rule_clash.mrs'
    path: ./sukkaw_ruleset/awavenue_ads_rule_clash.mrs
    proxy: Proxy

rules:
  - RULE-SET,reject_non_ip,Block
  - RULE-SET,reject_domainset,Block
  - RULE-SET,reject_non_ip_drop,REJECT-DROP
  - RULE-SET,reject_non_ip_no_drop,Block
  - RULE-SET,reject_awavenue_ads_rule,Block
  - RULE-SET,pcdn,Block

  - RULE-SET,jp,日本
  - RULE-SET,site_dmm,日本
  - RULE-SET,site_dlsite,日本
  - RULE-SET,custom_proxy,Proxy
  - RULE-SET,custom_direct,DIRECT
  - RULE-SET,custom_ai,AI
  - RULE-SET,site_googlefcm,Proxy
  - RULE-SET,asmr,ASMR
  - RULE-SET,site_pixiv,Pixiv
  - RULE-SET,site_youtube,Youtube

  - RULE-SET,ai_non_ip,AI
  - RULE-SET,microsoft_cdn_non_ip,DIRECT
  
  - RULE-SET,lan_non_ip,DIRECT
  - RULE-SET,cdn_domainset,Proxy
  - RULE-SET,cdn_non_ip,Proxy

  - RULE-SET,domestic_non_ip,DIRECT
  - RULE-SET,direct_non_ip,DIRECT
  - RULE-SET,download_domainset,Download
  - RULE-SET,download_non_ip,Download
  - RULE-SET,microsoft_non_ip,Proxy
  - RULE-SET,global_non_ip,Proxy
  - RULE-SET,site_geolocation_non_cn,Proxy
  
  - RULE-SET,telegram_ip,Proxy
  - RULE-SET,reject_ip,REJECT
  
  - RULE-SET,domestic_ip,DIRECT
  - RULE-SET,lan_ip,DIRECT
  - RULE-SET,china_ip,DIRECT
  - MATCH,Match
