# url 里填写自己的订阅,名称不能重复
log-level: warning
proxy-providers:
  provider1:
    url: ""
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204", interval: 300}

mixed-port: 31193
ipv6: false
allow-lan: false
unified-delay: false
tcp-concurrent: false
external-controller: 127.0.0.1:41193
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  device: TsuinoSora
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  strict-route: true
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  cache-algorithm: arc
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver: # 默认域名解析, 如不配置 fallback/proxy-server-nameserver, 则都由 nameserver 解析
    # - system://
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy: # 局域网域名不应使用公共DNS进行解析
    'rule-set:lan_non_ip': system://

proxy-groups:

  - name: Proxy
    type: select
    proxies: [自动选择,全部节点,香港-Auto,台湾-Auto,日本-Auto,新加坡-Auto,美国-Auto,其它地区]

  - name: 全部节点
    type: select
    include-all: true
    exclude-type: direct
    exclude-filter: "订阅|官网|售后"

  - name: 自动选择
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|🇺🇸|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)(?!.*(?:家宽|专用)).*)"
    exclude-filter: "订阅|官网|售后"
    tolerance: 20
    interval: 300
    lazy: true

  - name: Block
    type: select
    proxies: [REJECT,Proxy,DIRECT]

  - name: Pixiv
    type: select
    proxies: [Pixiv-auto,日本,Proxy,全部节点]
    url: "https://www.pixiv.net"
    interval: 300

  - name: ASMR
    type: select
    proxies: [ASMR-auto,Proxy,全部节点,DIRECT]
    url: "https://asmr.one"
    interval: 300

  - name: Youtube
    type: select
    proxies: [Youtube-auto,Proxy,全部节点]
    url: "https://www.youtube.com"
    interval: 300

  - name: Pixiv-auto
    type: url-test
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore)(?!.*(?:家宽|专用)).*)"
    url: "https://www.pixiv.net"
    interval: 300
    tolerance: 30
    hidden: true
    lazy: true

  - name: ASMR-auto
    type: url-test
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore)(?!.*(?:家宽|专用)).*)"
    url: "https://asmr.one"
    interval: 300
    tolerance: 30
    hidden: true
    lazy: true

  - name: Youtube-auto
    type: url-test
    url: "https://www.youtube.com"
    include-all: true
    filter: "(?i)(?=.*(?:🇭🇰|🇯🇵|🇸🇬|🇨🇳|🇺🇸|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates|D1)(?!.*(?:家宽|专用)).*)"
    tolerance: 20
    interval: 300
    hidden: true
    lazy: true
    
  - name: AI
    type: select
    proxies:  [美国-Auto,Proxy]

  - name: Download
    type: select
    proxies:  [DIRECT,Proxy]

  - name: Match
    type: select
    proxies:  [DIRECT,Proxy]


  #分隔,下面是地区分组
  - name: 香港-Auto
    type: url-test
    include-all: true
    filter: "(?i)港|hk|hongkong|hong kong"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 台湾-Auto
    type: url-test
    include-all: true
    filter: "(?i)台|tw|taiwan"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 日本-Auto
    type: url-test
    include-all: true
    filter: "(?i)日|jp|japan"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 美国-Auto
    type: url-test
    include-all: true
    filter: "(?i)美|us|unitedstates|united states"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 新加坡-Auto
    type: url-test
    include-all: true
    filter: "(?i)(新|sg|singapore)"
    exclude-filter: "订阅|官网|售后"
    interval: 300
    hidden: true
    tolerance: 30

  - name: 日本
    type: select
    proxies: [日本-Auto]
    include-all: true
    filter: "(?i)日本|jp|japan"

  - name: 其它地区
    type: select
    include-all: true
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"
    exclude-filter: "订阅|官网|售后"

rule-providers-anchor: # 锚点 如合并时有重复的项, 则不会去合并; 锚点名不能包含特殊字符
  rule_domain: &rule_domain {type: http, behavior: domain, format: mrs, interval: 43200}
  rule_ipcidr: &rule_ipcidr {type: http, behavior: ipcidr, format: mrs, interval: 43200}
  rule_classical: &rule_classical {type: http, behavior: classical, format: yaml, interval: 43200}

rule-providers:
  pcdn:
    type: http
    url: "https://raw.githubusercontent.com/uselibrary/PCDN/refs/heads/main/pcdn.list"
    format: text
    interval: 43200
    behavior: classical

  custom_direct:
      type: http
      url: "https://raw.githubusercontent.com/YRSB/MihomoRule/master/custom_direct.yaml"
      format: yaml
      interval: 43200
      behavior: classical
  
  custom_proxy:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/master/custom_proxy.yaml"
    format: yaml
    interval: 43200
    behavior: classical

  asmr:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/master/asmr.yaml"
    format: yaml
    interval: 43200
    behavior: domain

  jp:
    type: http
    url: "https://raw.githubusercontent.com/YRSB/MihomoRule/master/jp.yaml"
    format: yaml
    interval: 43200
    behavior: classical

  site_googlefcm:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs'

  site_pixiv:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs'

  site_youtube:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs'

  site_geolocation_non_cn:
    <<: *rule_domain
    url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs'

  reject_non_ip_no_drop:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt
    path: ./sukkaw_ruleset/reject_non_ip_no_drop.txt

  reject_non_ip_drop:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt
    path: ./sukkaw_ruleset/reject_non_ip_drop.txt

  reject_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/reject.txt
    path: ./sukkaw_ruleset/reject_non_ip.txt

  reject_domainset:
    type: http
    behavior: domain
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/domainset/reject.txt
    path: ./sukkaw_ruleset/reject_domainset.txt

  reject_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/reject.txt
    path: ./sukkaw_ruleset/reject_ip.txt

  ai_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./sukkaw_ruleset/ai_non_ip.txt

  telegram_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/telegram.txt
    path: ./sukkaw_ruleset/telegram_ip.txt

  microsoft_cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
    path: ./sukkaw_ruleset/microsoft_cdn_non_ip.txt

  microsoft_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
    path: ./sukkaw_ruleset/microsoft_non_ip.txt

  lan_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./sukkaw_ruleset/lan_non_ip.txt

  lan_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
    path: ./sukkaw_ruleset/lan_ip.txt

  domestic_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
    path: ./sukkaw_ruleset/domestic_non_ip.txt

  direct_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
    path: ./sukkaw_ruleset/direct_non_ip.txt

  global_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
    path: ./sukkaw_ruleset/global_non_ip.txt

  domestic_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
    path: ./sukkaw_ruleset/domestic_ip.txt

  china_ip:
    type: http
    behavior: ipcidr
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
    path: ./sukkaw_ruleset/china_ip.txt

  download_domainset:
    type: http
    behavior: domain
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/domainset/download.txt
    path: ./sukkaw_ruleset/download_domainset.txt

  download_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/download.txt
    path: ./sukkaw_ruleset/download_non_ip.txt

  cdn_domainset:
    type: http
    behavior: domain
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./sukkaw_ruleset/cdn_domainset.txt

  cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./sukkaw_ruleset/cdn_non_ip.txt

rules:
  - RULE-SET,reject_non_ip,Block
  - RULE-SET,reject_domainset,Block
  - RULE-SET,reject_non_ip_drop,REJECT-DROP
  - RULE-SET,reject_non_ip_no_drop,Block
  - RULE-SET,pcdn,Block

  - RULE-SET,jp,日本
  - RULE-SET,custom_proxy,Proxy
  - RULE-SET,custom_direct,DIRECT
  - AND,((DST-PORT,5228-5230),(RULE-SET,site_googlefcm)),DIRECT
  - RULE-SET,asmr,ASMR
  - RULE-SET,site_pixiv,Pixiv
  - RULE-SET,site_youtube,Youtube

  - RULE-SET,ai_non_ip,AI
  - RULE-SET,microsoft_cdn_non_ip,DIRECT
  
  - RULE-SET,lan_non_ip,DIRECT
  - RULE-SET,cdn_domainset,Proxy
  - RULE-SET,cdn_non_ip,Proxy

  - RULE-SET,domestic_non_ip,DIRECT
  - RULE-SET,direct_non_ip,DIRECT
  - RULE-SET,download_domainset,Download
  - RULE-SET,download_non_ip,Download
  - RULE-SET,microsoft_non_ip,Proxy
  - RULE-SET,global_non_ip,Proxy
  - RULE-SET,site_geolocation_non_cn,Proxy
  
  - RULE-SET,telegram_ip,Proxy
  - RULE-SET,reject_ip,REJECT
  
  - RULE-SET,domestic_ip,DIRECT
  - RULE-SET,lan_ip,DIRECT
  - RULE-SET,china_ip,DIRECT
  - MATCH,Match